version: "3.8"

services:
  url-checker:
    build: .
    image: forez/web-url-checker:latest
    ports:
      - "8080:80"
    volumes:
      - ./plugins/web-directory-free.zip:/tmp/web-directory-free.zip:ro
    environment:
      WP_VERSION: "6.8.2"
      WP_URL: "http://localhost:8080/cms"
      WP_TITLE: "Only local WordPress"
      WP_ADMIN_USER: "admin"
      WP_ADMIN_PASS: "<REDACTED>"
      WP_ADMIN_EMAIL: "admin@example.com"
      DB_NAME: "wordpress"
      DB_USER: "wp"
      DB_PASS: "<REDACTED>"
    deploy:
      resources:
        limits:
          memory: 1G
    networks:
      - public_web_url_checker_network

networks:
  public_web_url_checker_network:
    driver: bridge
